[discord]
guild_id = ""
clue_channel_id = ""
info_channel_id = ""

[discord.bot]
token = ""

[[users]]
id = ""
name = "Player1"

[[users]]
id = ""
name = "Player2"

[[users]]
id = ""
name = "Player3"

[[users]]
id = ""
name = "Player4"

[[users]]
id = ""
name = "Player5"

[[users]]
id = ""
name = "Player6"

[[users]]
id = ""
name = "Player7"

[[users]]
id = ""
name = "Player8"